### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by cantalupo555** [flathub/io.github.ferraridamiano.ConverterNOW#24] opened 2024-06-09 13:12 UTC
Hello, would it be possible to release ConverterNOW for ARM64?

The arm64 snap package does not work.
```
cantalupo@orangepi5:~$ snap run converternow
/snap/converternow/217/snap/command-chain/desktop-launch: line 605: /snap/converternow/217/bin/converternow: cannot execute binary file: Exec format error
/snap/converternow/217/snap/command-chain/desktop-launch: line 605: /snap/converternow/217/bin/converternow: Success
```

Anyway, I prefer flatpak packages.

Thanks!

**Comment by ferraridamiano** [comment] 2024-06-09 14:25
Closing as duplicate of:

- https://github.com/ferraridamiano/ConverterNOW/issues/205

I just shared a status update there

**Closed by ferraridamiano** 2024-06-09 14:25 UTC
